import Category from "@/components/Category";
import React from "react";


export const metadata = {
  title: "ISTAD - Categories",
  description: "Generated by create next app",
};


export default async function Categories() {
  

  return (
    <div className="flex min-h-screen flex-col items-center p-5">
      <h1 style={{ fontSize: "30px", color: "green", fontWeight: "bold",marginTop:"8px" }}>
        Category Management
      </h1>
      <div className="flex min-h-screen flex-wrap items-center justify-evenly">
        <Categories />
      </div>
    </div>
  );
}