import Product from "@/components/Product";
import React from "react";

export const metadata = {
  title: "ISTAD - Products",
  description: "Generated by create next app",
};

export default async function Products() {
  const products = await fetchProducts();

  return (
    <div className="flex min-h-screen flex-col items-center p-5">
      <h1 style={{ fontSize: "30px", color: "green", fontWeight: "bold",marginTop:"8px"}}>
        Product Management
      </h1>
      <div className="flex min-h-screen flex-wrap items-center justify-evenly">
        <Product />
      </div>
    </div>
  );
}

